from render_functions import *
def render(game,position,top_rot,left_elbow_rot,left_hand_rot,right_elbow_rot,right_hand_rot,bottom_rot,left_knee_rot,left_foot_rot,right_knee_rot,right_foot_rot,color=(255,255,255)):
  head = Vector2(0,-0.15)
  head.rotate(top_rot)

  shoulders = head * 2 / 3
  left_elbow = Vector2(-0.03,0)
  left_elbow.rotate(top_rot+left_elbow_rot)
  left_hand = Vector2(-0.03,0)
  left_hand.rotate(top_rot+left_elbow_rot+left_hand_rot)
  right_elbow = Vector2(0.03,0)
  right_elbow.rotate(top_rot+right_elbow_rot)
  right_hand = Vector2(0.03,0)
  right_hand.rotate(top_rot+right_elbow_rot+right_hand_rot)
  left_knee = Vector2(-0.03,0)
  left_knee.rotate(bottom_rot+left_knee_rot)
  left_foot = Vector2(0,0.05)
  left_foot.rotate(bottom_rot+left_knee_rot+left_foot_rot)
  right_knee = Vector2(0.03,0)
  right_knee.rotate(bottom_rot+right_knee_rot)
  right_foot = Vector2(0,0.05)
  right_foot.rotate(bottom_rot+right_knee_rot+right_foot_rot)
  position -= Vector2(0,max((left_foot+left_knee).y,(right_knee+right_foot).y))
  circle(game,position+head,0.04,color=color)
  line(game,position,head,width=5,color=color)
  
  line(game,position,left_knee,width=5,color=color)
  line(game,position+left_knee,left_foot,width=5,color=color)
  line(game,position,right_knee,width=5,color=color)
  line(game,position+right_knee,right_foot,width=5,color=color)
  line(game,position+shoulders,left_elbow,width=5,color=color)
  line(game,position+left_elbow+shoulders,left_hand,width=5,color=color)
  line(game,position+shoulders,right_elbow,width=5,color=color)
  line(game,position+right_elbow+shoulders,right_hand,width=5,color=color)
